language: ruby
env:
  - secret_key_base=asdlkjfh23lkj4h23lkjehfsd7f8xc98zxvhxkvjhenrweefdxi99 aws_access_key_id=test_aws_access_key_id aws_secret_access_key=test_aws_secret_access_key fb_app_id=test_fb_app_id fb_app_secret=test_fb_app_secret prerender_io_token=test_prerender_token
rvm:
  - 2.3.1
script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake
addons:
  code_climate:
    repo_token:
      secure: eKtahgCOYZC/FzHgPSRYWLG/c7dRelaUZgCHV5TyoIn+akelAPRs+B334J8ahAfArLIVL2iUNpGQVdbDAMyQNd0BcQROkzj2qicGX5BTpaGRjDRHOVUDpevykZJl6oqy4WjvMevSp2xxY1ejZmbOwW/NzRQfSd79ekxGr+J0V/0=
notifications:
  slack:
    secure: G6VLedqT8kXanccqUeRRej2aXkR0SMFSwCBX/hbsNy+qoC7WSTFjMr98ijTn3eTykz1nBk+d2d2sfSm5dreIsl7jsF+eqHYKmZzGb13/YG6lvf2+GNyFduhoKJC3NWj1dqPO2QS+8g9YYBpGJIpnlp+PkSck5ewqd+mDXr53QbA=
