language: ruby
rvm:
- 2.1.1
- 2.0.0
addons:
  code_climate:
    repo_token:
      secure: AyQOyqFNV38SWjaZamo6a965Q2lEdRklSFTmyVHGfUua9OMspHoMzlJcHoVdFZ6m0pyrvl3iPPiNboDgYCpvStoGl+x9KBnobb/dNQSSqgPo77oH8ZVwwjytxYyUVrVUMuaGXLlXI8+T3YLhJB6UddjcZ/TS6GI1KgNi0lEoRn0=
