default: &default
  aws_access_key_id: <%= ENV["aws_access_key_id"] %>
  aws_secret_access_key: <%= ENV["aws_secret_access_key"] %>
  prerender_io_token: <%= ENV["prerender_io_token"] %>
  secret_key_base: <%= ENV["secret_key_base"] %>
  secret_token: <%= ENV["secret_token"] %>

test: *default
development: *default
staging: *default
production: *default
